Basic rendering of project list and project details page
stefan096/UKS pull request #22
Opened 2020-01-18 17:43 UTC by kristina-grujic

Bez ikakvih stilova, osnovne informacije.

Lista projekata trenutno sadrzi sve projekte ikada, nakon dodavanja mogucnosti autentifikacije treba izmeniti da se filtrira za trenutnog korisnika

2020-01-18 17:49 UTC, stefan096 approved these changes

2020-01-19 11:09 UTC, stefan096 requested changes

2020-01-19 11:09 UTC, stefan096 commented on miniGithub/templates/miniGithub/base.html
> +    <title>Mini Github</title>
Kad smo se dogovorili za ime :D

2020-01-19 11:09 UTC, stefan096 commented on miniGithub/urls.py
> +    path('', views.projects_view, name="projects"),
trebala si napraviti novi fajl za projekte. Napravi novi fajl pa u njeag prekopiraj svoj metode

2020-01-19 11:09 UTC, stefan096 commented on miniGithub/urls.py
> +    path('projects/<int:project_id>/', views.project_view, name='project_details'),
isto kao i gore

2020-01-19 11:11 UTC, merged

2020-01-19 11:13 UTC, kristina-grujic commented on miniGithub/templates/miniGithub/base.html
> +    <title>Mini Github</title>
Dogovoricemo se :D

2020-01-19 11:14 UTC, kristina-grujic commented on miniGithub/urls.py
> +    path('', views.projects_view, name="projects"),
Kao sto sam rekla u DM, pravim ovu izmenu u iducem PR-u